### ISSUE TITLE
Missing Moves

### ISSUE THREAD

**Issue by LeonHammerla** [jacksonthall22/SAN-strings#1]
Here are some missing moves that i found, which can occur:

['Bxa8+', 'Bxa1+', 'Bxh1+', 'Bxh1', 'Bxh8', 'Bxa8', 'Bxh8+', 'Bxa1']

**Comment by jacksonthall22** [comment]
Interesting, also looks like there are some impossible moves in there:
- `Ba8xb7`
- `Ba8xc6`
- `Ba8xd5`
- `Ba8xe4`
- `Ba8xf3`
- `Ba8xg2`

I will have a look when I get the chance. Thanks!

**Comment by jacksonthall22** [comment]
> also looks like there are some impossible moves in there:

Hmm, peeking at this again and it looks like I was wrong here. Some of these are actually possible:
* `Ba8xb7`: Possible with Bs on `a8`, `a6`, `c8`
* `Ba8xc6`: Possible with Bs on `a8`, `a4`, `e8`
* `Ba8xd5`: Possible with Bs on `a8`, `a2`, `g8`
* `Ba8xe4`: Impossible, would require `a(-1)`, `i8` squares
* `Ba8xf3`: Impossible, would require `a(-3)`, `k8` squares
* `Ba8xg2`: Impossible, would require `a(-5)`, `m8` squares

So to generalize on a bishop move from square `A` to square `B`:
- Add file discriminators iff `B` is not a corner square
- Add rank discriminators iff mirroring `A` vertically about `B`'s rank produces a real board square
- Add full-square discriminators iff both of the above are true and mirroring `A` horizontally about `B`'s file produces a real board square

Am I missing anything?

**Comment by jacksonthall22** [comment]
Realize these points are off topic for your original question, opening a separate issue.

**Comment by jacksonthall22** [comment]
I totally revamped the generation algorithm. Thanks for these test cases, it helped me realize some deep issues with the code. They are all now generated correctly.
